// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// CCIterate
List CCIterate(int nIter, NumericMatrix old, NumericMatrix old_ll, bool single, int burn, IntegerMatrix N, NumericMatrix n);
RcppExport SEXP _QuantFit_CCIterate(SEXP nIterSEXP, SEXP oldSEXP, SEXP old_llSEXP, SEXP singleSEXP, SEXP burnSEXP, SEXP NSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type old(oldSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type old_ll(old_llSEXP);
    Rcpp::traits::input_parameter< bool >::type single(singleSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(CCIterate(nIter, old, old_ll, single, burn, N, n));
    return rcpp_result_gen;
END_RCPP
}
// CCIterateSingle
List CCIterateSingle(int nIter, NumericMatrix old, NumericMatrix old_ll, int burn, IntegerMatrix N, NumericMatrix n);
RcppExport SEXP _QuantFit_CCIterateSingle(SEXP nIterSEXP, SEXP oldSEXP, SEXP old_llSEXP, SEXP burnSEXP, SEXP NSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type old(oldSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type old_ll(old_llSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(CCIterateSingle(nIter, old, old_ll, burn, N, n));
    return rcpp_result_gen;
END_RCPP
}
// CCIterateDouble
List CCIterateDouble(int nIter, NumericMatrix old, NumericMatrix old_ll, int burn, IntegerMatrix N, NumericMatrix n);
RcppExport SEXP _QuantFit_CCIterateDouble(SEXP nIterSEXP, SEXP oldSEXP, SEXP old_llSEXP, SEXP burnSEXP, SEXP NSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type old(oldSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type old_ll(old_llSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(CCIterateDouble(nIter, old, old_ll, burn, N, n));
    return rcpp_result_gen;
END_RCPP
}
// CCIterateTriple
List CCIterateTriple(int nIter, NumericMatrix old, NumericMatrix old_ll, int burn, IntegerMatrix N, NumericMatrix n);
RcppExport SEXP _QuantFit_CCIterateTriple(SEXP nIterSEXP, SEXP oldSEXP, SEXP old_llSEXP, SEXP burnSEXP, SEXP NSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type old(oldSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type old_ll(old_llSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(CCIterateTriple(nIter, old, old_ll, burn, N, n));
    return rcpp_result_gen;
END_RCPP
}
// lsqisotonic
NumericVector lsqisotonic(NumericVector x, NumericVector y, NumericVector w);
RcppExport SEXP _QuantFit_lsqisotonic(SEXP xSEXP, SEXP ySEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(lsqisotonic(x, y, w));
    return rcpp_result_gen;
END_RCPP
}
// ksdensity
double ksdensity(NumericVector data, double point);
RcppExport SEXP _QuantFit_ksdensity(SEXP dataSEXP, SEXP pointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type point(pointSEXP);
    rcpp_result_gen = Rcpp::wrap(ksdensity(data, point));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_QuantFit_CCIterate", (DL_FUNC) &_QuantFit_CCIterate, 7},
    {"_QuantFit_CCIterateSingle", (DL_FUNC) &_QuantFit_CCIterateSingle, 6},
    {"_QuantFit_CCIterateDouble", (DL_FUNC) &_QuantFit_CCIterateDouble, 6},
    {"_QuantFit_CCIterateTriple", (DL_FUNC) &_QuantFit_CCIterateTriple, 6},
    {"_QuantFit_lsqisotonic", (DL_FUNC) &_QuantFit_lsqisotonic, 3},
    {"_QuantFit_ksdensity", (DL_FUNC) &_QuantFit_ksdensity, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_QuantFit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
