# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CCIterate <- function(nIter, old, old_ll, single, burn, N, n) {
    .Call(`_QuantFit_CCIterate`, nIter, old, old_ll, single, burn, N, n)
}

CCIterateSingle <- function(nIter, old, old_ll, burn, N, n) {
    .Call(`_QuantFit_CCIterateSingle`, nIter, old, old_ll, burn, N, n)
}

CCIterateDouble <- function(nIter, old, old_ll, burn, N, n) {
    .Call(`_QuantFit_CCIterateDouble`, nIter, old, old_ll, burn, N, n)
}

CCIterateTriple <- function(nIter, old, old_ll, burn, N, n) {
    .Call(`_QuantFit_CCIterateTriple`, nIter, old, old_ll, burn, N, n)
}

lsqisotonic <- function(x, y, w) {
    .Call(`_QuantFit_lsqisotonic`, x, y, w)
}

ksdensity <- function(data, point) {
    .Call(`_QuantFit_ksdensity`, data, point)
}

